version: 2.1
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: cimg/node:18.8.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Create page
          command: npm run build
      - run:
          name: Post to gh-pages
          command: curl ci-cd.net/v1/gh/pages | bash -s docs/.
      - run:
          name: CloufFlare - Purge everything
          command: |
            curl -X DELETE "https://api.cloudflare.com/client/v4/zones/${CF_ZONE}/purge_cache" \
             -H "X-Auth-Email: ${CF_EMAIL}" \
             -H "X-Auth-Key: ${CF_API_KEY}" \
             -H "Content-Type: application/json" \
             --data '{"purge_everything":true}'
workflows:
  version: 2.1
  website:
    jobs:
      - build:
          context: globalenv
          filters:
            branches:
              only:
                - main
